name: qtaralnada
description: sharah Qatar al Nada wa bal al Sada.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.9.2
  bdd_widget_test: ^1.2.1
  build_runner: ^2.4.9
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/data.json
   - assets/img/
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoN.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri.ttf
    - family: Noor
      fonts:
        - asset: assets/fonts/noorehuda.ttf
  
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  color: "#B89B72"  # Background color of splash screen
  image: assets/img/head_drawer.png  # Path to your splash logo image
  android: true
  ios: true
  web: false
  fullscreen: true  # Optional: To make the splash fullscreen